spring:
   profiles:
      active:
      - default
---
spring:
  profiles: dev
  application:
      name: microconfig-test-dev
  server:test-dev    
---
spring:
 profiles: default
 application:
      name: microconfig-test-default
 server:test-default